
//A gravidade da Lua é cerca de 17% do da Terra. Faça um programa em Java
//que calcule seu peso na Lua.

//meu peso=85.5
// gravidade lua=18%
public class Gravidadelua{
	
	public static void main (String[] args) {
	
		//variveis
	    double peso=85.5;
	    double peso_na_lua;
	
	    //operação
	    peso_na_lua=peso*0.18;
	    
	    //saída
	
    	System.out.println("O meu peso na lua é " + peso_na_lua );
	}
	
	
}
